spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket: youngcha-board-service
    region:
      static: ap-northeast-2
    stack:
      auto: false

server:
  port: 7010